### ISSUE TITLE
only small grey box appearing

### ISSUE THREAD

**Issue by midick** [AdamTillou/vim-imager#1]
when enabling vim-imager it only converts the line defining an image to a one character wide grey box. Ueberzug works fine in ranger though.
Do you have an idea what might be the cause of this?

**Comment by benzanol** [comment]
Thanks for letting me know.
It looks like the old method of loading images with Ueberzug (the one I was using) got deprecated. I updated the script, and it seems to work again. Try re-downloading the plugin it and let me know if it works!

**Comment by midick** [comment]
thank you so much!
it works like a charm now
